# ==============================================================================
# Generate Model Checksums
# ==============================================================================
# Scans the models/ directory for .pt model files, computes SHA-256 hashes,
# and writes them to models/checksums.json for production integrity verification.
#
# Usage:
#   Rscript scripts/generate_model_checksums.R
#
# Run this script after training new models or updating model files to keep
# checksums.json in sync. The checksums are used by .verify_model_integrity()
# in functions/ml_inference.R when MARINESABRES_VERIFY_MODELS=TRUE.
# ==============================================================================

if (!requireNamespace("digest", quietly = TRUE)) {
  stop("Package 'digest' is required. Install with: install.packages('digest')")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  stop("Package 'jsonlite' is required. Install with: install.packages('jsonlite')")
}

# Find all .pt files under models/
models_dir <- "models"
if (!dir.exists(models_dir)) {
  stop("models/ directory not found. Run this script from the project root.")
}

pt_files <- list.files(models_dir, pattern = "\\.pt$", recursive = TRUE, full.names = TRUE)

if (length(pt_files) == 0) {
  cat("No .pt files found in", models_dir, "\n")
  quit(status = 0)
}

cat(sprintf("Found %d model files. Computing SHA-256 checksums...\n", length(pt_files)))

# Compute hashes
checksums <- list()
for (f in pt_files) {
  # Store relative path from models/ (e.g., "connection_predictor_best.pt" or "ensemble/model_1_seed42.pt")
  rel_path <- sub("^models/", "", f)
  hash <- digest::digest(file = f, algo = "sha256")
  checksums[[rel_path]] <- hash
  cat(sprintf("  %s  %s\n", hash, rel_path))
}

# Build JSON structure
output <- list(
  `_comment` = paste(
    "SHA-256 checksums for ML model integrity verification.",
    "Generated by scripts/generate_model_checksums.R.",
    "In production, set MARINESABRES_VERIFY_MODELS=TRUE to enable verification."
  ),
  `_generated` = format(Sys.Date(), "%Y-%m-%d"),
  models = checksums
)

# Write to checksums.json
output_path <- file.path(models_dir, "checksums.json")
jsonlite::write_json(output, output_path, pretty = TRUE, auto_unbox = TRUE)

cat(sprintf("\nWrote %d checksums to %s\n", length(checksums), output_path))
cat("Done.\n")
